# configuration file

general:
    startupdelay: 15           # set delay in seconds before first generation (useful on startup to wait for KeePassXC to start before) 
    startserver: true          # set 'false' to prevent starting RSS server (just store data to local files), default: true
    port: 8080                 # RSS feed port, default 8080
    refreshtime: 3600          # time in seconds between consecutive RSS generator loop iterations, default 3600
    dataroot: "data"           # path to store data; path absolute or relative to config directory
                               # default value is app dir inside user home directory
    logdir: "log"              # path to store logs; path absolute or relative to config directory
                               # default value is app dir inside user home directory
    logviewer: "gedit %s"      # command line to view log file, %s will be replaced with log path

item:
    - parser: "logging"                     # parser identifier ("logging") - parser prepared to read logs generated by Python's "logging" module 
      enabled: true                         # is parser enabled
      params:                               # parameters passed to generator's constructor
        name: "app"                         # parser name (part of output path) 
        logfile: "/var/log/app_log.txt"     # iniput log file path
        # log entry format as in configuration of Python's logging module
        fmt: "%(asctime)s,%(msecs)-3d %(levelname)-8s %(threadName)s %(name)s:%(funcName)s [%(filename)s:%(lineno)d] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"        # datetime format as in configuration of Python's logging module
        loglevel: "WARNING"                 # log level threshold (same as in Python's logging module)
